=== ChenHaoyuan/xmlcourse-web/source/first_experiment/pictureLibrary.dtd
<!ELEMENT pictureLibrary (picture+)>
  <!ELEMENT picture  (title?,id,position,labels,category,describe)>
  <!ELEMENT title    (#PCDATA)>
  <!ELEMENT id       (#PCDATA)>
  <!ELEMENT position (#PCDATA)>
  
  <!ELEMENT labels   (label+)>
  <!ELEMENT label    (#PCDATA)>
  
  <!ELEMENT category   (#PCDATA)>
   
  <!ELEMENT describe  (pictureDescription,EnglishDescription,resolution,size,photoGraphers,copyright)>
  <!ELEMENT pictureDescription   (#PCDATA)>
  <!ELEMENT EnglishDescription   (#PCDATA)>
  <!ELEMENT resolution   (#PCDATA)>
  <!ELEMENT size   (#PCDATA)>
  <!ELEMENT photoGraphers   (#PCDATA)>
  <!ELEMENT copyright   (#PCDATA)>
  
  <!ATTLIST pictureLibrary source CDATA #FIXED "www.quanjing.com">
  <!ATTLIST picture format CDATA #REQUIRED>
  <!ATTLIST labels labelsQuantity CDATA #REQUIRED>

=== ChenHaoyuan/xmlcourse-web/source/second_experiment/2-1/pictureLibrary.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="pictureLibrary.css"?>
<!DOCTYPE pictureLibrary SYSTEM "pictureLibrary.dtd">
<pictureLibrary source="www.quanjing.com">
    <picture format="jpg">
        <title>果味</title>
        <id>iblgvi02075257</id>
        <position>http://www.quanjing.com/imgbuy/iblgvi02075257.html</position>
        <labels labelsQuantity="5">
            <label>果味</label>
            <label>胶冻</label>
            <label>甜食</label>
            <label>委内瑞拉</label>
            <label>烹饪</label>
        </labels>
        <category>美食</category>
        <describe>
            <pictureDescription>Fruity jelly sweets, Venezuela, recipe available for a fee</pictureDescription>
            <EnglishDescription>Fruity jelly sweets, Venezuela, recipe available for a fee</EnglishDescription>
            <resolution>3612x4838</resolution>
            <size>49M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>壁炉架</title>
        <id>sps4285-5737</id>
        <position>http://www.quanjing.com/imgbuy/sps4285-5737.html</position>
        <labels labelsQuantity="5">
            <label>客厅</label>
            <label>壁炉</label>
            <label>燃烧</label>
            <label>火</label>
            <label>地产</label>
        </labels>
        <category>家居</category>
        <describe>
            <pictureDescription>LIVING ROOM WITH FIREPLACE AND BURNING FIRE. Property Released</pictureDescription>
            <EnglishDescription>LIVING ROOM WITH FIREPLACE AND BURNING FIRE. Property Released</EnglishDescription>
            <resolution>4063x5076</resolution>
            <size>59M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>沉闷的</title>
        <id>mf700-06685215</id>
        <position>http://www.quanjing.com/imgbuy/mf700-06685215.html</position>
        <labels labelsQuantity="8">
            <label>更衣室</label>
            <label>和海滩</label>
            <label>小屋</label>
            <label>在冬季</label>
            <label>奥斯蒂亚</label>
            <label>丽都</label>
            <label>罗马</label>
            <label>意大利</label>
        </labels>
        <category>壁纸</category>
        <describe>
            <pictureDescription>Bathhouse and Beach Huts in Winter, Ostia Lido, Rome, Italy</pictureDescription>
            <EnglishDescription>Bathhouse and Beach Huts in Winter, Ostia Lido, Rome, Italy</EnglishDescription>
            <resolution>5100x3404</resolution>
            <size>49M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>青绿色</title>
        <id>rob-795-392</id>
        <position>http://www.quanjing.com/imgbuy/rob-795-392.html</position>
        <labels labelsQuantity="5">
            <label>马尔代夫</label>
            <label>照片</label>
            <label>旅游</label>
            <label>风景</label>
            <label>地形</label>
        </labels>
        <category>旅游</category>
        <describe>
            <pictureDescription>Aerial view of resort, Maldives, Indian Ocean, Asia</pictureDescription>
            <EnglishDescription>Aerial view of resort, Maldives, Indian Ocean, Asia</EnglishDescription>
            <resolution>5616x3744</resolution>
            <size>60M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>寂静</title>
        <id>263-1314</id>
        <position>http://www.quanjing.com/imgbuy/263-1314.html</position>
        <labels labelsQuantity="5">
            <label>旅行</label>
            <label>照片</label>
            <label>旅游</label>
            <label>风景</label>
            <label>城市</label>
        </labels>
        <category>旅游</category>
        <describe>
            <pictureDescription>http://www.quanjing.com/imgbuy/263-1314.html</pictureDescription>
            <EnglishDescription>N/A</EnglishDescription>
            <resolution>2912x4368</resolution>
            <size>36M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>气缸</title>
        <id>mf866-03581667</id>
        <position>http://www.quanjing.com/imgbuy/mf866-03581667.html</position>
        <labels labelsQuantity="7">
            <label>商标</label>
            <label>特写</label>
            <label>鼻子</label>
            <label>宝马</label>
            <label>视野</label>
            <label>概念</label>
            <label>展示</label>
        </labels>
        <category>汽车</category>
        <describe>
            <pictureDescription>Contact Masterfile for Trademark Release Availability - Detail nose view of the BMW Vision Effi...</pictureDescription>
            <EnglishDescription>Contact Masterfile for Trademark Release Availability - Detail nose view of the BMW Vision EfficientDynamics Concept show car. The new concept is a plug-in hybrid with a three cylinder turbo-diesel engine. Seen at the Los Angeles International Auto Show</EnglishDescription>
            <resolution>5125x3417</resolution>
            <size>50M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>那不勒斯湾</title>
        <id>iblhco01999201</id>
        <position>http://www.quanjing.com/imgbuy/iblhco01999201.html</position>
        <labels labelsQuantity="7">
            <label>黄色</label>
            <label>历史</label>
            <label>地区</label>
            <label>阿拉贡</label>
            <label>意大利</label>
            <label>欧洲</label>
            <label>区域</label>
        </labels>
        <category>汽车</category>
        <describe>
            <pictureDescription>Yellow Ferrari in the historic district of Ischia Ponte, Castello Aragonese castle, Ischia, Gul...</pictureDescription>
            <EnglishDescription>Yellow Ferrari in the historic district of Ischia Ponte, Castello Aragonese castle, Ischia, Gulf of Naples, Campania region, Italy, Europe</EnglishDescription>
            <resolution>5616x3744</resolution>
            <size>60M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(不需要肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>锉</title>
        <id>is096-056</id>
        <position>http://www.quanjing.com/imgbuy/is096-056.html</position>
        <labels labelsQuantity="4">
            <label>疗法</label>
            <label>美容</label>
            <label>化妆</label>
            <label>手</label>
        </labels>
        <category>时尚</category>
        <describe>
            <pictureDescription>女子接受美甲护理</pictureDescription>
            <EnglishDescription>Woman receiving manicure treatment</EnglishDescription>
            <resolution>3797x5700</resolution>
            <size>61M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(有肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>健身意识</title>
        <id>gws483218058</id>
        <position>http://www.quanjing.com/imgbuy/gws483218058.html</position>
        <labels labelsQuantity="5">
            <label>特写</label>
            <label>女青年</label>
            <label>张嘴</label>
            <label>照片</label>
            <label>护理</label>
        </labels>
        <category>时尚</category>
        <describe>
            <pictureDescription>Close-up of a young woman with her mouth open</pictureDescription>
            <EnglishDescription>Close-up of a young woman with her mouth open</EnglishDescription>
            <resolution>3388x5100</resolution>
            <size>49M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(有肖像权)</copyright>
        </describe>
    </picture>
    <picture format="jpg">
        <title>婴儿室</title>
        <id>gws483218058</id>
        <position>http://www.quanjing.com/imgbuy/gws483218058.html</position>
        <labels labelsQuantity="5">
            <label>白色</label>
            <label>婴儿床</label>
            <label>供给</label>
            <label>毛巾</label>
            <label>室内</label>
        </labels>
        <category>壁纸</category>
        <describe>
            <pictureDescription>A white cradle and baby's supplies</pictureDescription>
            <EnglishDescription>A white cradle and baby's supplies</EnglishDescription>
            <resolution>4580x4584</resolution>
            <size>60M</size>
            <photoGraphers>N/A</photoGraphers>
            <copyright>肖像权(有肖像权)</copyright>
        </describe>
    </picture>
</pictureLibrary>
